apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextjsbasicapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nextjsbasicapp.ms.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nextjsbasicapp-service
                port:
                  number: 80
